
- name: Configure MOTD Banner
  hosts: all
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Set MOTD Banner
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ motd_message }}"
        state: present